apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-java-demo
  labels:
    app: app-java-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-java-demo
  template:
    metadata:
      labels:
        app: app-java-demo
    spec:
      containers:
      - name: app-java-demo
        image: hackytackytimesawacky/app-java-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
          - name: regcred
